# This is a basic workflow to help you get started with Actions
name: Azure Service via TF

on:
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow this workflow to be called from another workflow and accept a working-directory input
  workflow_call:
    inputs:
      working-directory:
        required: false
        description: "Add the Service folder path like aks, vm, vmss etc..."
        type: string

jobs:
  AKS_Deployment:
    runs-on: ubuntu-latest
    env:
      TF_VAR_azure_subscription_id: ${{ secrets.SUBSCRIPTIONID }}
      TF_VAR_azure_client_id: ${{ secrets.CLIENTID }}
      TF_VAR_azure_client_secret: ${{ secrets.CLIENTSECRET }}
      TF_VAR_azure_tenant_id: ${{ secrets.TENANTID }}
    steps:        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialization
        run: |
          cd ${{ inputs.working-directory }}
          terraform init -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: |
          cd ${{ inputs.working-directory }}
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd ${{ inputs.working-directory }}
          terraform apply -auto-approve tfplan

      - name: ls -la
        run: |
          ls -la ${{ inputs.working-directory }}